[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "EnhancedUpgradeMenu"
description = "Enhances the upgrade management experience in MycoPunk with comparison mode, mass scrapping, filtering, and loadout expansion."
websiteUrl = "https://github.com/Little-Sparroh/EnhancedUpgradeMenu"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/EnhancedUpgradeMenu.dll"
target = "BepInEx/plugins/EnhancedUpgradeMenu.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]
